# Generated by Django 3.0.7 on 2020-06-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_choices', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('expected_need_in', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('issue_date', models.DateField(verbose_name='Purchase date(dd/mm/yy)')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('choices_field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invapp.Item_choices')),
            ],
        ),
    ]
