# Generated by Django 3.0.7 on 2020-06-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.IntegerField()),
                ('expected_need_in', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Purchase date(dd/mm/yy)')),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('choices_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='invapp.Item_choices')),
            ],
        ),
    ]
